version: "3"

services:
    web:
        build: .
        working_dir: /usr/src/app/app/app
        environment:
            FLASK_ENV: development
            FLASK_APP: application.py
        ports:
            - '5000:5000'
        entrypoint:
            - flask
            - run
            - --host=0.0.0.0
        # volumes:
        #     - .:/usr/src/app
